import {
  AGENT_DOC_MARKDOWN_PATHS,
  agentMarkdown,
  base,
  ignorePatterns,
  json,
  markdown,
  sorting,
} from '@finografic/oxc-config/oxfmt';
import type { OxfmtConfig, OxfmtOverrideConfig } from '@finografic/oxc-config/oxfmt';
import { defineConfig } from 'oxfmt';

export default defineConfig({
  ignorePatterns: [
    ...ignorePatterns,
    // Generated by packages/icons/scripts/generate.ts (column-aligned registry); oxfmt would collapse padding.
    'packages/icons/src/icons.ts',
    'packages/icons/src/index.ts',
  ],
  ...base,
  ...sorting,
  overrides: [
    { files: ['*.json', '*.jsonc'], excludeFiles: [], options: { ...json } },
    {
      files: ['*.md', '*.mdx'],
      excludeFiles: [...AGENT_DOC_MARKDOWN_PATHS],
      options: { ...markdown },
    },
    {
      files: [...AGENT_DOC_MARKDOWN_PATHS],
      excludeFiles: [],
      options: { ...agentMarkdown },
    },
  ] satisfies OxfmtOverrideConfig[],
} satisfies OxfmtConfig);
