packages:
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@finografic/*'

onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks

overrides:
  pkg-types: 2.3.1
